# Site settings
title: Audible
client:
  name: Der Soundtrack zu Ihrer Reise
  link: "https://adbl.co/2JGgWZ7"
core-se-link: https://www.secretescapes.de/current-sales?utm_source=SE&utm_medium=hub&utm_campaign=audible_DE_2019
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=audible_DE_2019"
description: >
  Audiofans Achtung! Egal ob Sie Roadtrips, Spa-Auszeiten oder Strandurlaub vorziehen – oder alle drei – ein Podcast oder Hörspiel von Audible bereichert jede Reise um eine weitere Facette.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/audible" # the subpath of your site, e.g. /blog/
img:     "/de/audible/_assets/img"
css:     "/de/audible/_assets/css"
js:      "/de/audible/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
